-- argonaut.lua
-- Neovim port of the Argonaut terminal theme (as shipped with Ghostty)
-- Activate with :colorscheme argonaut
-- Set vim.g.argonaut_transparent = true before loading to let the terminal background show through

local function blend(fg, bg, alpha)
	local function rgb(hex)
		return tonumber(hex:sub(2, 3), 16), tonumber(hex:sub(4, 5), 16), tonumber(hex:sub(6, 7), 16)
	end
	local fr, fg_, fb = rgb(fg)
	local br, bg_, bb = rgb(bg)
	local function mix(a, b) return math.floor(a * alpha + b * (1 - alpha) + 0.5) end
	return string.format("#%02x%02x%02x", mix(fr, br), mix(fg_, bg_), mix(fb, bb))
end

-- Argonaut palette (ANSI 0-15 + special colors), plus a few derived UI shades
local c = {
	bg         = "#0e1019",
	fg         = "#fffaf4",
	black      = "#232323",
	gray       = "#444444",
	red        = "#ff000f",
	red_br     = "#ff2740",
	green      = "#8ce10b",
	green_br   = "#abe15b",
	yellow     = "#ffb900",
	yellow_br  = "#ffd242",
	blue       = "#008df8",
	blue_br    = "#0092ff",
	magenta    = "#6d43a6",
	magenta_br = "#9a5feb",
	cyan       = "#00d8eb",
	cyan_br    = "#67fff0",
	white      = "#ffffff",
	cursor     = "#ff0018",
	pink       = "#ff8ca4", -- cursor-text
	selection  = "#002a3b",

	bg_dark    = "#090a10",
	bg_float   = "#131623",
	bg_hl      = "#191d2c",
	border     = "#2b3048",
	fg_dim     = "#b9b4ae",
	comment    = "#626780",
	linenr     = "#3a3f55",
}

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "argonaut"

local transparent = vim.g.argonaut_transparent == true
local bg = transparent and "NONE" or c.bg

local groups = {
	-- Editor
	Normal           = { fg = c.fg, bg = bg },
	NormalNC         = { fg = c.fg, bg = bg },
	NormalFloat      = { fg = c.fg, bg = c.bg_float },
	FloatBorder      = { fg = c.border, bg = c.bg_float },
	FloatTitle       = { fg = c.cyan, bg = c.bg_float, bold = true },
	Cursor           = { fg = c.pink, bg = c.cursor },
	lCursor          = { link = "Cursor" },
	CursorIM         = { link = "Cursor" },
	TermCursor       = { link = "Cursor" },
	CursorLine       = { bg = c.bg_hl },
	CursorColumn     = { bg = c.bg_hl },
	ColorColumn      = { bg = c.bg_float },
	CursorLineNr     = { fg = c.yellow, bold = true },
	LineNr           = { fg = c.linenr },
	SignColumn       = { fg = c.linenr, bg = bg },
	FoldColumn       = { fg = c.comment, bg = bg },
	Folded           = { fg = c.cyan, bg = c.bg_float, italic = true },
	VertSplit        = { fg = c.border },
	WinSeparator     = { fg = c.border },
	EndOfBuffer      = { fg = c.bg },
	NonText          = { fg = c.linenr },
	Whitespace       = { fg = c.linenr },
	SpecialKey       = { fg = c.linenr },
	Conceal          = { fg = c.comment },
	Visual           = { bg = c.selection },
	VisualNOS        = { bg = c.selection },
	Search           = { fg = c.bg, bg = c.yellow },
	IncSearch        = { fg = c.bg, bg = c.red_br, bold = true },
	CurSearch        = { link = "IncSearch" },
	Substitute       = { fg = c.bg, bg = c.red_br },
	MatchParen       = { fg = c.cyan_br, bold = true, underline = true },
	Directory        = { fg = c.blue_br },
	Title            = { fg = c.cyan, bold = true },
	ErrorMsg         = { fg = c.red_br, bold = true },
	WarningMsg       = { fg = c.yellow },
	ModeMsg          = { fg = c.fg, bold = true },
	MoreMsg          = { fg = c.green },
	Question         = { fg = c.blue_br },
	QuickFixLine     = { bg = c.selection, bold = true },
	WildMenu         = { fg = c.bg, bg = c.blue_br },

	Pmenu            = { fg = c.fg, bg = c.bg_float },
	PmenuSel         = { fg = c.white, bg = c.selection, bold = true },
	PmenuSbar        = { bg = c.bg_hl },
	PmenuThumb       = { bg = c.border },
	PmenuKind        = { fg = c.magenta_br, bg = c.bg_float },
	PmenuExtra       = { fg = c.comment, bg = c.bg_float },
	PmenuBorder      = { fg = c.border, bg = c.bg_float },

	StatusLine       = { fg = c.fg, bg = c.bg_float },
	StatusLineNC     = { fg = c.comment, bg = c.bg_dark },
	TabLine          = { fg = c.comment, bg = c.bg_dark },
	TabLineFill      = { bg = c.bg_dark },
	TabLineSel       = { fg = c.fg, bg = c.bg, bold = true },
	WinBar           = { fg = c.fg_dim, bg = bg },
	WinBarNC         = { fg = c.comment, bg = bg },

	SpellBad         = { undercurl = true, sp = c.red_br },
	SpellCap         = { undercurl = true, sp = c.yellow },
	SpellLocal       = { undercurl = true, sp = c.cyan },
	SpellRare        = { undercurl = true, sp = c.magenta_br },

	DiffAdd          = { bg = blend(c.green, c.bg, 0.15) },
	DiffChange       = { bg = blend(c.blue, c.bg, 0.15) },
	DiffDelete       = { fg = c.red, bg = blend(c.red, c.bg, 0.15) },
	DiffText         = { bg = blend(c.blue, c.bg, 0.35) },
	Added            = { fg = c.green },
	Changed          = { fg = c.yellow },
	Removed          = { fg = c.red_br },

	-- Syntax
	Comment          = { fg = c.comment, italic = true },
	Constant         = { fg = c.yellow_br },
	String           = { fg = c.green },
	Character        = { fg = c.green_br },
	Number           = { fg = c.yellow },
	Float            = { fg = c.yellow },
	Boolean          = { fg = c.yellow },
	Identifier       = { fg = c.fg },
	Function         = { fg = c.blue },
	Statement        = { fg = c.magenta_br },
	Conditional      = { fg = c.magenta_br },
	Repeat           = { fg = c.magenta_br },
	Label            = { fg = c.magenta_br },
	Operator         = { fg = c.red_br },
	Keyword          = { fg = c.magenta_br },
	Exception        = { fg = c.red_br },
	PreProc          = { fg = c.red_br },
	Include          = { fg = c.red_br },
	Define           = { fg = c.red_br },
	Macro            = { fg = c.red_br },
	PreCondit        = { fg = c.red_br },
	Type             = { fg = c.cyan },
	StorageClass     = { fg = c.magenta_br },
	Structure        = { fg = c.cyan },
	Typedef          = { fg = c.cyan },
	Special          = { fg = c.cyan_br },
	SpecialChar      = { fg = c.cyan_br },
	Tag              = { fg = c.red_br },
	Delimiter        = { fg = c.fg_dim },
	SpecialComment   = { fg = c.comment, bold = true },
	Debug            = { fg = c.red_br },
	Underlined       = { underline = true },
	Ignore           = { fg = c.linenr },
	Error            = { fg = c.red_br },
	Todo             = { fg = c.bg, bg = c.yellow, bold = true },

	-- Treesitter
	["@variable"]                   = { fg = c.fg },
	["@variable.builtin"]           = { fg = c.red_br, italic = true },
	["@variable.parameter"]         = { fg = c.pink },
	["@variable.parameter.builtin"] = { fg = c.pink, italic = true },
	["@variable.member"]            = { fg = c.cyan_br },
	["@property"]                   = { fg = c.cyan_br },
	["@constant"]                   = { fg = c.yellow_br },
	["@constant.builtin"]           = { fg = c.yellow, italic = true },
	["@constant.macro"]             = { fg = c.yellow_br },
	["@module"]                     = { fg = c.yellow_br },
	["@module.builtin"]             = { fg = c.yellow_br, italic = true },
	["@label"]                      = { fg = c.magenta_br },
	["@string"]                     = { fg = c.green },
	["@string.documentation"]       = { fg = blend(c.green, c.bg, 0.7), italic = true },
	["@string.regexp"]              = { fg = c.cyan_br },
	["@string.escape"]              = { fg = c.cyan_br },
	["@string.special"]             = { fg = c.cyan_br },
	["@string.special.symbol"]      = { fg = c.yellow_br },
	["@string.special.url"]         = { fg = c.cyan, underline = true },
	["@character"]                  = { fg = c.green_br },
	["@character.special"]          = { fg = c.cyan_br },
	["@boolean"]                    = { fg = c.yellow },
	["@number"]                     = { fg = c.yellow },
	["@number.float"]               = { fg = c.yellow },
	["@type"]                       = { fg = c.cyan },
	["@type.builtin"]               = { fg = c.cyan, italic = true },
	["@type.definition"]            = { fg = c.cyan },
	["@attribute"]                  = { fg = c.yellow_br },
	["@attribute.builtin"]          = { fg = c.yellow_br, italic = true },
	["@function"]                   = { fg = c.blue },
	["@function.builtin"]           = { fg = c.blue_br, italic = true },
	["@function.call"]              = { fg = c.blue },
	["@function.macro"]             = { fg = c.red_br },
	["@function.method"]            = { fg = c.blue },
	["@function.method.call"]       = { fg = c.blue },
	["@constructor"]                = { fg = c.cyan },
	["@operator"]                   = { fg = c.red_br },
	["@keyword"]                    = { fg = c.magenta_br },
	["@keyword.coroutine"]          = { fg = c.magenta_br, italic = true },
	["@keyword.function"]           = { fg = c.magenta_br },
	["@keyword.operator"]           = { fg = c.magenta_br },
	["@keyword.import"]             = { fg = c.red_br },
	["@keyword.type"]               = { fg = c.magenta_br },
	["@keyword.modifier"]           = { fg = c.magenta_br },
	["@keyword.repeat"]             = { fg = c.magenta_br },
	["@keyword.return"]             = { fg = c.red_br },
	["@keyword.debug"]              = { fg = c.red_br },
	["@keyword.exception"]          = { fg = c.red_br },
	["@keyword.conditional"]        = { fg = c.magenta_br },
	["@keyword.directive"]          = { fg = c.red_br },
	["@punctuation.delimiter"]      = { fg = c.fg_dim },
	["@punctuation.bracket"]        = { fg = c.fg_dim },
	["@punctuation.special"]        = { fg = c.cyan_br },
	["@comment"]                    = { link = "Comment" },
	["@comment.documentation"]      = { link = "Comment" },
	["@comment.error"]              = { fg = c.bg, bg = c.red_br, bold = true },
	["@comment.warning"]            = { fg = c.bg, bg = c.yellow, bold = true },
	["@comment.todo"]               = { fg = c.bg, bg = c.cyan, bold = true },
	["@comment.note"]               = { fg = c.bg, bg = c.blue_br, bold = true },
	["@tag"]                        = { fg = c.red_br },
	["@tag.builtin"]                = { fg = c.red_br },
	["@tag.attribute"]              = { fg = c.yellow_br, italic = true },
	["@tag.delimiter"]              = { fg = c.fg_dim },
	["@markup.heading.1"]           = { fg = c.red_br, bold = true },
	["@markup.heading.2"]           = { fg = c.yellow, bold = true },
	["@markup.heading.3"]           = { fg = c.green, bold = true },
	["@markup.heading.4"]           = { fg = c.cyan, bold = true },
	["@markup.heading.5"]           = { fg = c.blue_br, bold = true },
	["@markup.heading.6"]           = { fg = c.magenta_br, bold = true },
	["@markup.strong"]              = { bold = true },
	["@markup.italic"]              = { italic = true },
	["@markup.strikethrough"]       = { strikethrough = true },
	["@markup.underline"]           = { underline = true },
	["@markup.quote"]               = { fg = c.comment, italic = true },
	["@markup.math"]                = { fg = c.cyan_br },
	["@markup.link"]                = { fg = c.blue_br },
	["@markup.link.label"]          = { fg = c.blue_br },
	["@markup.link.url"]            = { fg = c.cyan, underline = true },
	["@markup.raw"]                 = { fg = c.green_br },
	["@markup.list"]                = { fg = c.red_br },
	["@markup.list.checked"]        = { fg = c.green },
	["@markup.list.unchecked"]      = { fg = c.comment },
	["@diff.plus"]                  = { link = "Added" },
	["@diff.minus"]                 = { link = "Removed" },
	["@diff.delta"]                 = { link = "Changed" },

	-- LSP semantic tokens (let treesitter win for plain variables)
	["@lsp.type.variable"]                     = {},
	["@lsp.type.selfParameter"]                = { link = "@variable.builtin" },
	["@lsp.type.decorator"]                    = { link = "@attribute" },
	["@lsp.type.builtinConstant"]              = { link = "@constant.builtin" },
	["@lsp.type.magicFunction"]                = { link = "@function.builtin" },
	["@lsp.typemod.function.defaultLibrary"]   = { link = "@function.builtin" },
	["@lsp.typemod.variable.defaultLibrary"]   = { link = "@variable.builtin" },
	["@lsp.typemod.variable.readonly"]         = { link = "@constant" },
	LspReferenceText                           = { bg = c.bg_hl },
	LspReferenceRead                           = { bg = c.bg_hl },
	LspReferenceWrite                          = { bg = c.bg_hl, underline = true },
	LspInlayHint                               = { fg = c.comment, bg = blend(c.comment, c.bg, 0.1), italic = true },
	LspSignatureActiveParameter                = { fg = c.yellow, bold = true },
	LspInfoBorder                              = { link = "FloatBorder" },

	-- Diagnostics
	DiagnosticError            = { fg = c.red_br },
	DiagnosticWarn             = { fg = c.yellow },
	DiagnosticInfo             = { fg = c.blue_br },
	DiagnosticHint             = { fg = c.cyan },
	DiagnosticOk               = { fg = c.green },
	DiagnosticVirtualTextError = { fg = c.red_br, bg = blend(c.red_br, c.bg, 0.1) },
	DiagnosticVirtualTextWarn  = { fg = c.yellow, bg = blend(c.yellow, c.bg, 0.1) },
	DiagnosticVirtualTextInfo  = { fg = c.blue_br, bg = blend(c.blue_br, c.bg, 0.1) },
	DiagnosticVirtualTextHint  = { fg = c.cyan, bg = blend(c.cyan, c.bg, 0.1) },
	DiagnosticUnderlineError   = { undercurl = true, sp = c.red_br },
	DiagnosticUnderlineWarn    = { undercurl = true, sp = c.yellow },
	DiagnosticUnderlineInfo    = { undercurl = true, sp = c.blue_br },
	DiagnosticUnderlineHint    = { undercurl = true, sp = c.cyan },
	DiagnosticUnnecessary      = { fg = c.comment },
	DiagnosticDeprecated       = { strikethrough = true },

	-- vim-signify / gitsigns
	SignifySignAdd    = { fg = c.green },
	SignifySignChange = { fg = c.yellow },
	SignifySignDelete = { fg = c.red_br },
	GitSignsAdd       = { fg = c.green },
	GitSignsChange    = { fg = c.yellow },
	GitSignsDelete    = { fg = c.red_br },

	-- nvim-cmp
	CmpItemAbbr              = { fg = c.fg },
	CmpItemAbbrMatch         = { fg = c.blue_br, bold = true },
	CmpItemAbbrMatchFuzzy    = { fg = c.blue_br },
	CmpItemAbbrDeprecated    = { fg = c.comment, strikethrough = true },
	CmpItemMenu              = { fg = c.comment },
	CmpItemKindFunction      = { link = "@function" },
	CmpItemKindMethod        = { link = "@function.method" },
	CmpItemKindConstructor   = { link = "@constructor" },
	CmpItemKindVariable      = { fg = c.fg_dim },
	CmpItemKindField         = { link = "@variable.member" },
	CmpItemKindProperty      = { link = "@property" },
	CmpItemKindClass         = { link = "@type" },
	CmpItemKindInterface     = { link = "@type" },
	CmpItemKindStruct        = { link = "@type" },
	CmpItemKindEnum          = { link = "@type" },
	CmpItemKindEnumMember    = { link = "@constant" },
	CmpItemKindConstant      = { link = "@constant" },
	CmpItemKindModule        = { link = "@module" },
	CmpItemKindKeyword       = { link = "@keyword" },
	CmpItemKindSnippet       = { fg = c.magenta_br },
	CmpItemKindText          = { fg = c.green },
	CmpItemKindFile          = { fg = c.blue_br },
	CmpItemKindFolder        = { fg = c.blue_br },

	-- neo-tree
	NeoTreeNormal            = { fg = c.fg, bg = transparent and "NONE" or c.bg_dark },
	NeoTreeNormalNC          = { fg = c.fg, bg = transparent and "NONE" or c.bg_dark },
	NeoTreeWinSeparator      = { fg = c.border, bg = transparent and "NONE" or c.bg_dark },
	NeoTreeEndOfBuffer       = { fg = c.bg_dark },
	NeoTreeRootName          = { fg = c.cyan, bold = true },
	NeoTreeDirectoryName     = { fg = c.blue_br },
	NeoTreeDirectoryIcon     = { fg = c.blue_br },
	NeoTreeFileName          = { fg = c.fg },
	NeoTreeIndentMarker      = { fg = c.linenr },
	NeoTreeExpander          = { fg = c.comment },
	NeoTreeDotfile           = { fg = c.comment },
	NeoTreeGitAdded          = { fg = c.green },
	NeoTreeGitModified       = { fg = c.yellow },
	NeoTreeGitDeleted        = { fg = c.red_br },
	NeoTreeGitUntracked      = { fg = c.magenta_br },
	NeoTreeGitConflict       = { fg = c.red, bold = true },
	NeoTreeGitIgnored        = { fg = c.comment },
	NeoTreeFloatBorder       = { link = "FloatBorder" },
	NeoTreeTitleBar          = { fg = c.bg, bg = c.cyan, bold = true },

	-- noice / notify
	NoiceCmdlinePopupBorder        = { fg = c.cyan },
	NoiceCmdlinePopupTitle         = { fg = c.cyan, bold = true },
	NoiceCmdlineIcon               = { fg = c.cyan },
	NoiceCmdlinePopupBorderSearch  = { fg = c.yellow },
	NoiceCmdlineIconSearch         = { fg = c.yellow },
	NotifyERRORBorder = { fg = blend(c.red_br, c.bg, 0.5) },
	NotifyWARNBorder  = { fg = blend(c.yellow, c.bg, 0.5) },
	NotifyINFOBorder  = { fg = blend(c.blue_br, c.bg, 0.5) },
	NotifyDEBUGBorder = { fg = c.border },
	NotifyTRACEBorder = { fg = blend(c.magenta_br, c.bg, 0.5) },
	NotifyERRORIcon   = { fg = c.red_br },
	NotifyWARNIcon    = { fg = c.yellow },
	NotifyINFOIcon    = { fg = c.blue_br },
	NotifyDEBUGIcon   = { fg = c.comment },
	NotifyTRACEIcon   = { fg = c.magenta_br },
	NotifyERRORTitle  = { fg = c.red_br },
	NotifyWARNTitle   = { fg = c.yellow },
	NotifyINFOTitle   = { fg = c.blue_br },
	NotifyDEBUGTitle  = { fg = c.comment },
	NotifyTRACETitle  = { fg = c.magenta_br },

	-- which-key
	WhichKey          = { fg = c.cyan },
	WhichKeyGroup     = { fg = c.blue_br },
	WhichKeyDesc      = { fg = c.magenta_br },
	WhichKeySeparator = { fg = c.comment },
	WhichKeyNormal    = { link = "NormalFloat" },
	WhichKeyBorder    = { link = "FloatBorder" },

	-- treesitter-context
	TreesitterContext           = { bg = c.bg_float },
	TreesitterContextLineNumber = { fg = c.comment, bg = c.bg_float },
	TreesitterContextBottom     = { underline = true, sp = c.border },

	-- vim-illuminate
	IlluminatedWordText  = { bg = c.bg_hl },
	IlluminatedWordRead  = { bg = c.bg_hl },
	IlluminatedWordWrite = { bg = c.bg_hl, underline = true },

	-- mini.indentscope
	MiniIndentscopeSymbol = { fg = c.magenta },

	-- nvim-scrollbar
	ScrollbarHandle = { bg = c.bg_hl },
	ScrollbarError  = { fg = c.red_br },
	ScrollbarWarn   = { fg = c.yellow },
	ScrollbarInfo   = { fg = c.blue_br },
	ScrollbarHint   = { fg = c.cyan },

	-- nvim-dap
	DapBreakpoint = { fg = c.red_br },
	DapStopped    = { fg = c.green },

	-- neotest
	NeotestPassed      = { fg = c.green },
	NeotestFailed      = { fg = c.red_br },
	NeotestRunning     = { fg = c.yellow },
	NeotestSkipped     = { fg = c.cyan },
	NeotestNamespace   = { fg = c.magenta_br },
	NeotestFile        = { fg = c.cyan },
	NeotestDir         = { fg = c.blue_br },
	NeotestAdapterName = { fg = c.red_br, bold = true },
	NeotestFocused     = { bold = true, underline = true },
	NeotestIndent      = { fg = c.linenr },
	NeotestExpandMarker = { fg = c.linenr },
	NeotestWinSelect   = { fg = c.cyan, bold = true },
	NeotestTest        = { fg = c.fg },
}

for group, opts in pairs(groups) do
	vim.api.nvim_set_hl(0, group, opts)
end

-- :terminal colors
local term = {
	c.black, c.red, c.green, c.yellow, c.blue, c.magenta, c.cyan, c.white,
	c.gray, c.red_br, c.green_br, c.yellow_br, c.blue_br, c.magenta_br, c.cyan_br, c.white,
}
for i, color in ipairs(term) do
	vim.g["terminal_color_" .. (i - 1)] = color
end
